package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Up'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Up")) {
    params {
        add {
            password("env.BOT_TOKEN", "credentialsJSON:6a0b19ab-3765-454f-9103-49ff1acabe87", display = ParameterDisplay.HIDDEN)
        }
        add {
            password("env.POSTGRES_PASSWORD", "credentialsJSON:93abc2d6-85ac-48e4-9410-d21613885080", display = ParameterDisplay.HIDDEN)
        }
        add {
            text("env.ASPNETCORE_ENVIRONMENT", "Production", allowEmpty = false)
        }
    }
}
