package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Up'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Up")) {
    params {
        add {
            password("env.BOT_TOKEN", "credentialsJSON:6a0b19ab-3765-454f-9103-49ff1acabe87", display = ParameterDisplay.HIDDEN)
        }
        add {
            password("env.POSTGRES_PASSWORD", "credentialsJSON:93abc2d6-85ac-48e4-9410-d21613885080", display = ParameterDisplay.HIDDEN)
        }
        add {
            text("env.ASPNETCORE_ENVIRONMENT", "Production", allowEmpty = false)
        }
        add {
            password("env.JWT_KEY", "credentialsJSON:1367a739-5fae-41ff-9a3d-26e141ef03fa", display = ParameterDisplay.HIDDEN)
        }
    }

    expectSteps {
        exec {

            conditions {
                contains("teamcity.agent.jvm.os.name", "Windows")
            }
            path = "build.cmd"
            arguments = "Up --skip"
        }
        exec {

            conditions {
                doesNotContain("teamcity.agent.jvm.os.name", "Windows")
            }
            path = "build.sh"
            arguments = "Up --skip"
        }
    }
    steps {
        insert(2) {
            step {
                name = "Production docker-compose configuration"
                type = "MRPP_CreateTextFile"
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/docker-compose.override.yml")
                param("content", """
                    version: '3.9'
                    
                    services:
                      host:
                        environment:
                          - ASPNETCORE_ENVIRONMENT=%env.ASPNETCORE_ENVIRONMENT%
                        networks:
                          - caffe_menu_bot_network
                    
                    networks:
                      caffe_menu_bot_network:
                        external:
                          name: postgres_network
                """.trimIndent())
            }
        }
    }
}
