package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.ExecBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Up'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Up")) {
    params {
        add {
            text("env.ASPNETCORE_ENVIRONMENT", "Production", label = "aspnetcore_environment", allowEmpty = false)
        }
        add {
            password("env.POSTGRES_PASSWORD", "credentialsJSON:fde04986-c090-4fc0-a00d-41321166f346", label = "postgres_password", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
    }

    expectSteps {
        exec {
            path = "build.sh"
            arguments = "Up --skip"
        }
    }
    steps {
        insert(0) {
            step {
                name = "Production docker-compose configuration"
                type = "MRPP_CreateTextFile"
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/docker-compose.override.yml")
                param("content", """
                    version: '3.9'
                    
                    services:
                      host:
                        environment:
                          - ASPNETCORE_ENVIRONMENT=%env.ASPNETCORE_ENVIRONMENT%
                        networks:
                          - caffe_menu_bot_network
                    
                    networks:
                      caffe_menu_bot_network:
                        external:
                          name: postgres_network
                """.trimIndent())
            }
        }
        insert(1) {
            step {
                name = "Production database settings"
                type = "MRPP_CreateTextFile"
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/CaffeMenuBot.AppHost/dbsettings.Production.json")
                param("content", """
                    {
                        "ConnectionStrings": {
                            "CaffeMenuBotDb": "Host=caffe_menu_bot_postgres;Port=5432;UserId=postgres;Password=%env.POSTGRES_PASSWORD%;Database=caffe_menu_bot;CommandTimeout=300;"
                        }
                    }
                """.trimIndent())
            }
        }
        update<ExecBuildStep>(2) {
            clearConditions()
        }
        insert(3) {
            step {
                name = "Production application settings"
                type = "MRPP_CreateTextFile"
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/CaffeMenuBot.AppHost/appsettings.Production.json")
                param("content", """
                    {
                      "Logging": {
                        "LogLevel": {
                          "Default": "Information",
                          "Microsoft": "Warning",
                          "Microsoft.Hosting.Lifetime": "Information"
                        }
                      },
                      "IdentityServer": {
                        "Key": {
                          "Type": "Development"
                        }
                      }
                    }
                """.trimIndent())
            }
        }
    }
}
