version: '3.9'

x-restart-policy: &restart_policy
  restart: unless-stopped

x-host-config: &host_config
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
  ports:
    - "5000:80"

services:
  host:
    << : *restart_policy
    << : *host_config
    container_name: caffe_menu_bot_host
    image: caffe_menu_bot/host:latest
    build:
      context: .
      dockerfile: CaffeMenuBot.AppHost/Dockerfile